---
  api_key:
    description: "PagerDuty API Key"
    type: "string"
    secret: true
    required: true
  service_key:
    description: "PagerDuty Service Key"
    type: "string"
    secret: true
    required: true
  debug:
    description: "Set to True to enable additional logging"
    type: "boolean"
    secret: false
    default: false
